name: Service Unit Tests
run-name: Mangine Service Unit Tests
on: 
  workflow_dispatch:
  pull_request:
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake
      - name: Compile Unit Tests
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
      - name: Execute Unit Tests
        run: |
          cd build
          ./service_gt